apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached-mautic
  labels:
    app: mautic
spec:
  selector:
    matchLabels:
      app: mautic
      tier: memcached-mautic
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: mautic
        tier: memcached-mautic
    spec:
      containers:
      - name: memcached-mautic
        image: ubuntu/memcached:edge
        env:
        - name: MEMCACHED_CACHE_SIZE
          value: "128"
        - name: MEMCACHED_MAX_CONNECTIONS
          value: "2048"
        - name: MEMCACHED_THREADS
          value: "8"
        - name: MEMCACHED_USERNAME
          value: "hostingbyalitech"
        - name: MEMCACHED_PASSWORD
          value: "5&T#0upcg96xYBz2u2"
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: memcached-mautic-service
spec:
  ports:
    - port: 11211
  selector:
    app: mautic
    tier: memcached-mautic