apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-mautic
  labels:
    app: mautic
spec:
  selector:
    matchLabels:
      app: mautic
      tier: redis-mautic
  strategy:
    type: Recreate
  replicas: 2
  template:
    metadata:
      labels:
        app: mautic
        tier: redis-mautic
    spec:
      containers:
      - name: redis-mautic
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-mautic-service
spec:
  ports:
    - port: 6379
  selector:
    app: mautic
    tier: redis-mautic